version: '3.7'

services:
  postgres-master:
    image: postgres:14.8-alpine3.18
    container_name: postgres-master
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5000:5432
    volumes:
      - "./common/master:/var/lib/postgresql/data"
    env_file:
      - .env

  postgres-slave-1:
    image: postgres:14.8-alpine3.18
    container_name: postgres-slave-1
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5001:5432
    volumes:
      - "./common/slave_1:/var/lib/postgresql/data"
    env_file:
      - .env

  postgres-slave-2:
    image: postgres:14.8-alpine3.18
    container_name: postgres-slave-2
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5002:5432
    volumes:
      - "./common/slave_2:/var/lib/postgresql/data"
    env_file:
      - .env
  
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
    command:
      - '--memory-limit=1024'