version: '3.7'

services:
  redis-pub-sub:
    image: redis:6.2-alpine
    container_name: redis-pub-sub
    restart: on-failure
    ports:
      - "6379:6379"
  
  redis-1:
    image: redis:6.2-alpine
    container_name: redis-1
    restart: on-failure
    ports:
      - "6479:6379"

  redis-2:
    image: redis:6.2-alpine
    container_name: redis-2
    restart: on-failure
    ports:
      - "6579:6379"
    
  redis-3:
    image: redis:6.2-alpine
    container_name: redis-3
    restart: on-failure
    ports:
      - "6679:6379"
